# Site settings
title: Rainist
subtitle: 세상을 촉촉하게 만드는 사람들
email: rainist@rainist.com
description: 레이니스트를 소개하며, 레이니스트 팀이 배운 교훈들을 공유하는 웹사이트입니다.

url: "http://rainist.com"

# Build settings
markdown: kramdown
markdown_ext: "md"

# Output
permalink: pretty

# Pagination
paginate: 5
paginate_path: "page/:num/"

# Members
members: [
  {
    url: "/assets/profile_sample.png",
    name: "황이슬",
    job: "UX/UI 디자이너",
    desc: "황이슬씨는 레이니스트 채용에 빈틈을 찾게 해준 사람입니다. 우리는 매일 그녀를 뽑지 말앗어야 했다고 인성면접을 봤어야 했다고 우리의 채용과정을 반성합니다. 황이슬씨 이후 우리는 착한 사람들만 뽑으려고 합니다.",
    card: "외환 2X 알파",
    product: "KB 동물농장 적금"
  },
  {
    url: "/assets/profile_sample.png",
    name: "황성현",
    job: "씨티오",
    desc: "민사고 졸업한 특급 엘리트인줄 알았으나, 깔깔깔!@# 하는 웃음소리로 여친에게 구박받는 개발자이다. 그는 사내연애 중이다.",
    card: "외환 2X 알파",
    product: "KB 동물농장 적금"
  }
]
