# Site settings
title: Rainist
subtitle: 세상을 촉촉하게 만드는 사람들
email: rainist@rainist.com
description: 레이니스트를 소개하며, 레이니스트 팀이 배운 교훈들을 공유하는 웹사이트입니다.

url: "http://rainist.com"

# Build settings
markdown: kramdown
markdown_ext: "md"
gems: [jekyll-paginate]

# Pagination
paginate: 5
paginate_path: "blog/:num/"
permalink: "blog/:year/:month/:day/:slug"

# CEO
ceo: {
    img_small: "/assets/profile_sample.png",
    img_large: "/assets/profile_sample.png",
    name: "김태훈",
    job: "CEO",
    desc: "호떡왕",
    card: "외환 2X 알파",
    product: "KB 동물농장 적금"
}

# Members (Team. product)
members_product: [
    {
        img_small: "/assets/profile_kym_small.png",
        img_large: "/assets/profile_kym_large.png",
        name: "김여민",
        job: "마케터",
        desc: "황이슬씨는 레이니스트 채용에 빈틈을 찾게 해준 사람입니다. 우리는 매일 그녀를 뽑지 말앗어야 했다고 인성면접을 봤어야 했다고 우리의 채용과정을 반성합니다. 황이슬씨 이후 우리는 착한 사람들만 뽑으려고 합니다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_khm_small.png",
        img_large: "/assets/profile_khm_large.png",
        name: "김현민",
        job: "인턴",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_psj_small.png",
        img_large: "/assets/profile_psj_large.png",
        name: "권수진",
        job: "마케터",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_pmr_small.png",
        img_large: "/assets/profile_pmr_large.png",
        name: "박미륵",
        job: "개발자",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_pjs_small.png",
        img_large: "/assets/profile_pjs_large.png",
        name: "박지수",
        job: "디자이너",
        desc: "박지수님은 상남자입니다. 지푸라기 같은 마른 몸에서 발산되는 과도한 남성호르몬이 걱정입니다. 어머니가 긴급 처방으로 사주신 분홍색 패딩으로 겨우겨우 여자 행세를 하고 있습니다. 25년동안 울산 사투리를 고치기 위해 필사적으로 노력했지만 대표이사를 필두로 경상도 비율이 50%인 회사에 잘못 입사했습니다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_bjw_small.png",
        img_large: "/assets/profile_bjw_large.png",
        name: "변재원",
        job: "개발자",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_sjy_small.png",
        img_large: "/assets/profile_sjy_large.png",
        name: "서자영",
        job: "디자이너",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_asw_small.png",
        img_large: "/assets/profile_asw_large.png",
        name: "안성원",
        job: "마케터",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_jia_small.png",
        img_large: "/assets/profile_jia_large.png",
        name: "전인아",
        job: "개발자",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_jyj_small.png",
        img_large: "/assets/profile_jyj_large.png",
        name: "정유진",
        job: "개발자",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_joj_small.png",
        img_large: "/assets/profile_joj_large.png",
        name: "조욱진",
        job: "마케터",
        desc: "민사고 졸업한 특급 엘리트인줄 알았으나, 깔깔깔!@# 하는 웃음소리로 여친에게 구박받는 개발자이다. 그는 사내연애 중이다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_hsh_small.png",
        img_large: "/assets/profile_hsh_large.png",
        name: "황성현",
        job: "개발자",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_his_small.png",
        img_large: "/assets/profile_his_large.png",
        name: "황이슬",
        job: "디자이너",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    }
]

# Members (Team. Data)
members_data: [
    {
        img_small: "/assets/profile_kkh_small.png",
        img_large: "/assets/profile_kkh_large.png",
        name: "김광훈",
        job: "광부",
        desc: "폭력배2",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_kch_small.png",
        img_large: "/assets/profile_kch_large.png",
        name: "김찬호",
        job: "광부",
        desc: "폭력배2",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_pki_small.png",
        img_large: "/assets/profile_pki_large.png",
        name: "박규인",
        job: "광부",
        desc: "폭력배1",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    },
    {
        img_small: "/assets/profile_ish_small.png",
        img_large: "/assets/profile_ish_large.png",
        name: "임소현",
        job: "광부",
        desc: "레이니스트 멤버 중 가장 여성스러우며, 독특한 질감의 옷이 보이면 만지는 습관이 있다.",
        card: "외환 2X 알파",
        product: "KB 동물농장 적금"
    }
]

# Press kit
presskit: "/assets/rainist_presskit.pdf"

# News
news: [
    {
        url: "http://m.news.naver.com/read.nhn?mode=LSD&mid=sec&sid1=004&oid=009&aid=0003671619",
        title: "김태훈 뱅크샐러드 대표 | 대형 카드사·은행이 먼저 찾아가는 ‘핀테크 청년’…“1년에 100만원씩 세이브해주는 앱(App) 완성하겠습니다”",
        media: "매일경제",
        date: "2016.01.22"
    },
    {
        url: "http://m.news.naver.com/read.nhn?mode=LSD&mid=sec&sid1=004&oid=009&aid=0003671619",
        title: "김태훈 뱅크샐러드 대표 | 대형 카드사·은행이 먼저 찾아가는 ‘핀테크 청년’…“1년에 100만원씩 세이브해주는 앱(App) 완성하겠습니다”",
        media: "매일경제",
        date: "2016.01.22"
    }
]

# Recruit
recruit: [
    {
        title: "뱅크샐러드 앱개발자 모집",
        date: "~ 2016.02.02",
        content: "recruit/notice_developer_160202.md"
    }
]
