title: Rainist
subtitle: 세상을 촉촉하게 만드는 사람들
email: rainist@rainist.com
description: 레이니스트를 소개하며, 레이니스트 팀이 배운 교훈들을 공유하는 웹사이트입니다.

url: "http://rainist.com"

markdown: kramdown
markdown_ext: "md"
gems: [jekyll-paginate]

paginate: 5
paginate_path: "blog/:num/"
permalink: "blog/:year/:month/:day/:slug"

presskit: "/assets/rainist_presskit.pdf"

recruit: [
    {
        title: "뱅크샐러드 앱개발자 모집",
        date: "~ 2016.02.02",
        content: "recruit/notice_developer_160202.md"
    }
]
