title: products development
desc: 제품 개발팀은 제품을 통해 문제를 해결하는 사람들입니다. 디자이너, 엔지니어, 마케터가 모두 모여 각자의 도메인에서 중요한 문제를 찾고 해결점을 만들어냅니다.
people:
    - name: 황성현
      position: CTO
      email: sunghyunzz@rainist.com
      desc: 성현님은 민사고 재학 시절 프로그래밍에 눈을 떠 성균관대학교 소프트웨어 학과에 진학했습니다. 하지만 대학 입학 직후 창업한 첫 번째 스타트업을 거쳐 레이니스트에 오기까지, 그가 학교를 다녔던 모습은 거의 한 번도 본 적이 없습니다. 대부분의 인생을 개발에 오롯이 바친 나머지, 그는 나이보다 원숙한 실력과 경험 그리고 외모를 자랑하며 이래저래 참 믿음직스러운 CTO를 담당하고 있습니다. 가끔 그의 나이를 모르는 사람들에게 퀴즈를 내곤 하는데  난이도가 스핑크스 문제 급입니다. 과연, 그는 몇 살일까요?
      card: 아시아나 삼성 애니패스 플래티늄
      product: 없음
    - name: 전인아
      position: Data Scientist
      email: inahjeon@rainist.com
      desc: 인아님은 성균관대 컴퓨터공학과를 졸업 한 뒤, 데이터 분석에 눈을 떠 카이스트에서 석사 학위를 취득했습니다. L전자를 다니던 그녀는 흡사 데이터를 찾는 하이에나였습니다. 세상의 모든 데이터를 분석해내겠다는 포부를 갖고 점점 더 많은 데이터를 쫓아 레이니스트에 합류하게 되었습니다. 지금은 뱅크샐러드의 머신러닝을 담당하고 있습니다. 그녀의 취미는 “누가 이렇게 했어? 왜 서버가 죽어?”라는 말을 감칠맛나게 하는 것이며 특기이자 재능은 “내가 그랬어? 미안해"하며 바로 정중한 사과를 하는 것입니다.
      card: 신한 삑
      product: 없음
    - name: 변재원
      position: Software Engineer
      email: astroplex@rainist.com
      desc: 네이버에서 프런트엔드를 담당했던 변재원님은 누구보다 마이크로한 감성을 지닌 개발자입니다. 그는 언제나 “이거 컬러가 조금 밸런스가 안 맞는데”라거나 “여기 1px 옮겨야 하지 않을까요?” 등의 섬세한 피드백을 들고 와 디자이너들의 감탄을 자아냅니다. 그의 섬세함은 비단 디자인 감각에만 드러나는 것이 아닙니다. 쇼핑 또한 그의 특출난 능력 중 하나인데, 10원까지 비교하는 꼼꼼함 덕분에 레이니스트의 모든 사무용품은 최저가로 구매할 수 있었습니다. 구매 대행도 가능하니 관심 있으시면 메일 주세요.
      card: 신한 Hi-Point
      product: 없음
    - name: 박미륵
      position: Software Engineer
      email: mireuk@rainist.com
      desc: 홍익대학교에서 도시공학을 배우던 미륵님은 갑자기 들어온 안드로이드 신의 부름을 받아 뜬금없는 개발을 시작하였습니다. 리모택시를 거쳐 누구보다 빠른 속도로 개발 실력을 쌓아왔는데 그의 성장 동력은 아무래도 노래 부르기인 것 같습니다. 그는 노래 부르며 개발하기를 즐기는데, 장르는 아이돌부터 90년대 음악까지 아주 다양합니다. 레이니스트는 그가 싱잉 아웃 라우드 할 수 있도록 코워킹 스페이스에서 단독 사무실로 빠르게 이사했습니다. 창피해서 그런 건 절대 아닙니다.
      card: NEW 우리 V / KDB 체크
      product: IBK 흔들어 적금 / KDB Hi 재형저축 / 하나은행 주택청약종합저축
    - name: 정유진
      position: Software Engineer
      email: gpeddler@rainist.com
      desc: 디지털 미디어 고등학교를 졸업 한 후 소프트웨어 마에스트로 과정을 밟던 유진님은 어린 나이에 스타트업의 길에 빠져 학교로 돌아가지 못하고 있는 창업 꿈나무입니다. 레이니스트에 합류하면서 너무 최선을 다하고 싶었던 나머지 도보 10분 거리의 고급 오피스텔로 이사하였으나, 월세를 감당하지 못하고 회사에서 라면을 먹으며 숙식하고 있습니다. 카페에서 일하는 것을 좋아하는 유진님은 사무실 자리에 앉아있는 날이 거의 없습니다. 신규 입사자가 오게 되면 그의 자리를 내어줄 예정입니다. 내어줘야겠습니다.
      card: 채움 NEW 농촌사랑 체크
      product: 없음
    - name: 이승용
      position: Software Engineer
      email: wdyd2004@rainist.com
      desc: 승용님은 세종과고 시절 국제정보올림피아드(IOI) 국가대표로 출전해 은메달을 따고 각종 알고리즘 대회를 휩쓸더니 그 성과로 서울대에 진학한 알고리즘 수재입니다. 뱅크샐러드의 모든 알고리즘 엔진은 그의 손을 거칩니다. 승용님은 나이에 어울리지 않는 어휘력과 걸음걸이, 온화한 미소로 인해 레이니스트의 부장님으로 불립니다. 특유의 친화력으로 인해 자상한 부장님인 줄 알았으나, 별거 아닌 일에 버럭하고 주말에도 나와서 일하라고 하는 모습은 누가 봐도 무한상사의 유부장입니다.
      card: 농협 TAKE5 / 농협 채움 Global 체크
      product: 삼성중국 본토영 포커스 증권 투자신탁 / 동부차이나 본토 증권자 투자신탁 / 마이홈플랜 주택청약종합저축합
    - name: 최현민
      position: Software Engineer
      email: hyunmin@rainist.com
      desc: 현민님은 민사고 재학 시절 한국정보올림피아드(KOI)의 금상을 수상하고, 서울대에 진학 후 대학생 프로그래밍 경시대회(ICPC) 국제 대회에 진출한 경력이 있는 엘리트입니다. 알고리즘에 특히 두각을 드러낸 현민님은 “정말 풀기 어려운 문제”가 있다는 선배 성현님의 말에 강한 호기심을 느껴 레이니스트의 합류하게 되었습니다. 머리에 든 게 너무 많아서인지 압도적인 머리둘레로 사내 머리 크기 1위 자리를 탈환하였습니다. 웃지 않을 때 보이는 그의 날카로운 눈매는 진시황의 병마용을 닮았습니다. 구글에 ‘병마용’을 검색하여 수많은 현민님을 만나보세요!
      card: 우리 다모아 체크
      product: 없음
    - name: 서자영
      position: CDO
      email: jayoung@rainist.com
      desc: 홍익대학교에서 산업디자인을 전공한 자영님은 음주를 즐겨 하여 맥주 추천 서비스 회사를 창업, 이를 운영하였습니다. 22세 어린 나이에 첫 창업을 시작한 그녀는 레이니스트의 여성 중 막내이지만 큰 언니같은 듬직함과 판단력으로 CDO를 맡고 있습니다. "들어봐 들어봐, 황성현 황성현" 등 두 번 연속으로 빠르게 말하기를 즐기는 그녀는 하루에 하나 씩 새로운 결심을 하는 버릇이 있습니다. 최근에는 인지심리학에 관심이 많아 영어 논문들을 읽다, 영어 공부를 해야겠다는 결심을 했으나 진척률은 들어본 바가 없습니다.
      card: 삼성 TAP TAP O / 외환 2X 알파
      product: 없음
    - name: 박지수
      position: UX.UI Designer
      email: jisu@rainist.com
      desc: 홍익대학교에서 산업디자인을 전공한 지수님은 칼 같은 디자인 감각과 사시미같은 성격을 지녔습니다. 어떤 모호한 시안들도 그녀의 손에 들어가면 칼같이 챙챙 잘려 나옵니다. 그녀의 생활 패턴 또한 칼 같은데, 10시 출근인 회사를 오기 위해 (회사가 30분 거리임에도 불구하고) 아침 7시 반부터 일어나서 낫또와 함께 아침식사를 한 뒤 9시 반 쯤 제일 일찍 회사에 도착합니다. 7시면 칼같이 퇴근하고 10시면 칼같이 취침을 합니다. 가끔 회식이라도 하는 날이면 10시부터 집에 가서 자야 한다고 울부짖습니다. 우리는 그녀가 참 신기합니다.
      card: 외환 2X 알파 / NEW 우리 V
      product: 우리은행 우리웰리치100적금
    - name: 황이슬
      position: UX.UI Designer
      email: dew@rainist.com
      desc: 이슬님은 경희대에서 시각디자인을 공부하던 중 중국어가 너무 배우고 싶어져 홀연 하얼빈으로 떠났다고 합니다. 그렇게 그녀는 종종 일이 잘 풀리지 않으면 홀연히 해외여행을 다녀오며 영감을 받곤 합니다. 우리는 그것이 정말 영감인지, 도피인지 알 수가 없습니다만 그래도 여행 후 열정을 불사르는 모습을 자주 목격합니다. 그녀의 취미는 아이콘 만드는 것인데, 그 아이콘은 팀원들에게 “내 아이스크림을 사 오지 않으면 네가 키우는 새싹을 밟겠어" 등의 협박 메시지를 보내는데 활용됩니다.
      card: KB 해피 nori 체크 / KB FINETECH (Basic 할인형)
      product: 국민은행 Smart★폰 적금 / KDB Hi 재형저축
    - name: 조욱진
      position: Marketer
      email: cho.ookjin@rainist.com
      desc: 욱진님은 서강대를 졸업하여 H 카드의 페이스북 황태자로 주목받던 찰나, 금융정보의 비대칭성을 해결하고자 하는 열정 하나로 레이니스트에 합류하였습니다. 그는 페이스북 콘텐츠 제작 중 마음에 드는 짤이 보이지 않자 직접 종이와 펜을 들고 그려내는 열정을 발휘하곤 합니다. 고객 CS 응답의 휴먼 터칭을 강조하던 그는 뱅크샐러드 사용자분에게 너무 감사하다는 칭찬과 함께 기프티콘을 받는 기염을 토하기도 했습니다. 줄 서서 한 모금씩 드세요, 이 커피는 무려 사용자분께서 보내주신 성수입니다!
      card: 현대카드 M2 Edition2
      product: 신한 직장IN플러스적금 / 마이홈플랜 주택청약종합저축
    - name: 권수진
      position: Marketer
      email: sujin@rainist.com
      desc: 서울여대에서 콘텐츠 디자인을 전공한 수진님은 디자인, 개발에도 발을 담갔던 다재다능한 마케터입니다. 그녀의 입사 소망은 “마케팅이 너무 하고 싶어요"였는데 지금은 홀로 10개가 넘는 마케팅 채널을 개설해 원 없이 하고 있습니다. 하루에 ‘연료'로 편의점 카페라떼 5통을 먹어치우는데 못 먹게 하면 금단현상 때문에 드립이 떠오르지 않는다고 울부짖습니다. 그녀의 새해 소망은 다이어트였는데 우리는 팀의 평화와 안정을 위해 카페라떼를 줘야 할지, 그녀의 소망을 위해 막아야 할지 항상 고민입니다.
      card: 우리 가득한 / 롯데 국민행복 / KB 혜담
      product: 우리 아가사랑 유후 적금 / 주택청약종합저축
    - name: 안성원
      position: Marketer
      email: sungwon@rainist.com
      desc: 레이니스트의 보도자료는 안성원님의 입사 전과 후로 나뉩니다. 성원님이 입사한 후 레이니스트와 뱅크샐러드를 다룬 기사가 급증하였고 그녀는 ‘HONORABLE’이란 칭호를 받았습니다. 또한 그녀는 마케팅을 잘 하기도 하고, 잘 당하기도 하는 역지사지 마케터인데 특히, 프로모션, 000한정판, 29cm에 취약합니다. 그녀의 특기는 저녁 10시즈음, 야근으로 지친 팀원들을 모두 29cm 이끌어 쇼핑을 하게 함으로써 사기를 높이는 것입니다. 그녀는 오늘도 수화기 너머 익숙한 목소리에 “네, 경비실앞에 놔주세요"라고 말합니다.
      card: 신한 Love / 신세계 씨티 리워드
      product: 국민은행 Smart★폰 적금
