title: products development
desc: 제품 개발팀은 제품을 통해 문제를 해결하는 사람들입니다. 디자이너, 엔지니어, 마케터가 모두 모여 각자의 도메인에서 중요한 문제를 찾고 해결점을 만들어냅니다.
people:
    - name: 황성현
      position: CTO
      email: sunghyunzz@rainist.com
      desc: 성현님은 민족사관고등학교를 졸업 후 성균관대학교에 진학했으나, 어린 나이에 창업의 길에 빠져 더 이상 학교로 돌아가지 못하고 있습니다. 그는 평소 온화하지만 개발이나 전략 이야기를 할 때에는 소름 돋는 천재로 변신합니다. 대신 신은 그에게 재능을 주고 생활력을 빼앗았습니다. 인생을 개발에 오롯이 바친 나머지 이케아 서랍장 하나 조립할 줄 모릅니다. 영화 매니아로 팀원들과 소통하고자 슬랙에 영화 채널을 뚫었지만 혼자 있습니다. 다 나가주세요.
      card: 아시아나 삼성 애니패스 플래티늄
      product: 없음
    - name: 전인아
      position: Data Scientist
      email: inahjeon@rainist.com
      desc: 인아님은 카이스트 석사 학위와 함께 대전을 탈출하여 L 전자에 입사하였습니다. 데이터 마이닝 연구실 출신인 그녀는 언제나 더 많은 데이터를 원했고, 결국 그녀는 모든 금융 데이터들이 모인다는 레이니스트에 합류하였습니다. 지금은 원했던 것 이상으로 많은 데이터로 인해 행복 포화 상태에 있습니다. 인아님은 “그럴 수 있어”라는 말을 좋아하는데, 요새 부쩍 그 말이 늘었다 싶은 건 기분 탓이겠죠.
      card: 신한 삑
      product: 없음
    - name: 변재원
      position: Software Engineer
      email: astroplex@rainist.com
      desc: 네이버에서 프런트엔드 개발을 하던 재원님은 더 어려운 웹사이트를 찾아 레이니스트에 합류하게 되었습니다. 기대 이상으로 어렵고 복잡한 뱅크샐러드 웹의 프런트엔드를 맡게 되자 그는 행복 포화 상태에 이르렀습니다. 재원님은 세상 거의 모든 브랜드를 사랑합니다. 레이니스트 모든 이들이 구매 전 지식쇼핑이나 블로그보다 변재원 검색을 먼저 찾습니다. 약은 약사에게, 쇼핑은 변재원에게!
      card: 신한 Hi-Point
      product: 없음
    - name: 박미륵
      position: Software Engineer
      email: mireuk@rainist.com
      desc: 리모택시를 거쳐 레이니스트에 합류한 미륵님은 개발하며 노래 부르기를 좋아합니다. 그가 싱잉 아웃 라우드 할 수 있도록 코워킹 스페이스에서 단독 사무실로 빠르게 이사했습니다. (창피해서 그런 건 아닙니다.) 사무실 이사 후로 마음껏 노래하고 있는데, 그의 인생 최고의 곡은 빅뱅의 뱅뱅뱅입니다. 조카를 너무 사랑한 나머지 자리에 사진을 도배해놓아 신규 입사자들에게 유부남으로 오해를 사고 있습니다.
      card: NEW 우리 V / KDB 체크
      product: IBK 흔들어 적금 / KDB Hi 재형저축 / 하나은행 주택청약종합저축
    - name: 정유진
      position: Software Engineer
      email: gpeddler@rainist.com
      desc: 유진님은 어린 나이에 스타트업의 길에 뛰어들어 학교로 돌아가지 못하고 있습니다. 레이니스트에 합류하여 너무 최선을 다하고 싶었던 나머지 출퇴근 도보 10분 거리의 언주역 소재 고급 오피스텔로 이사하였으나 월세를 감당하지 못하고 회사에서 라면을 먹으며 숙식하고 있습니다. 어떤 기능이든 디자인이든 순식간에 잘 만들어내 디자이너들이 그를 자주 찾고 있습니다.
      card: 채움 NEW 농촌사랑 체크
      product: 없음
    - name: 서자영
      position: CDO
      email: jayoung@rainist.com
      desc: 홍익대학교에서 산업디자인을 전공한 자영님은 "들어봐 들어봐, 황성현 황성현" 등 두 번 연속으로 빠르게 말하기를 즐깁니다. 음주를 즐겨 하여 맥주 추천 서비스 회사를 창업, 이를 운영하였습니다. 하루에 하나씩 새로운 결심을 하는 버릇이 있습니다. 최근에는 체화된 인지에 관심이 많아 영어 논문들을 읽다, 영어 공부를 해야겠다는 결심을 했으나 진척률은 들어본 바가 없습니다.
      card: 삼성 CJ ONE / 하나 해피포인트 체크
      product: 없음
    - name: 박지수
      position: UX.UI Designer
      email: jisu@rainist.com
      desc: 홍익대학교에서 산업디자인을 전공한 지수님은 레이니스트에서 상남자를 맡고 있습니다. 지푸라기 같은 마른 몸에서 발산되는 과도한 남성호르몬이 걱정입니다. 어머니가 긴급 처방으로 사주신 분홍색 패딩으로 겨우겨우 여자 행세를 하고 있습니다. 25년 동안 울산 사투리를 고치기 위해 필사적으로 노력했지만 대표이사를 필두로 사투리 비율이 50%인 회사에 잘못 입사했습니다.
      card: 외환 2X 알파 / NEW 우리 V
      product: 우리은행 우리웰리치100적금
    - name: 황이슬
      position: UX.UI Designer
      email: dew@rainist.com
      desc: 경희대학교에서 시각디자인을 전공한 이슬님은 레이니스트의 악마를 맡고 있습니다. 엄청난 열정으로 인턴십 기간 동안 최고의 디자이너로 찬사를 받았으나 정규직 전환과 동시에 큰 눈을 번뜩이는 악마로 돌변했습니다. 특기는 타인의 가장 소중한 것을 파괴하는 일로, 슬랙으로 이모티콘 협박 메시지 발송을 즐깁니다. 레이니스트 채용에 인적성 단계 도입이 시급합니다.
      card: KB 해피 nori 체크 / KB FINETECH (Basic 할인형)
      product: 국민은행 Smart★폰 적금 / KDB Hi 재형저축
    - name: 조욱진
      position: Marketer
      email: cho.ookjin@rainist.com
      desc: 조욱진님은 H캐피탈의 페이스북 황태자 출신으로, 순해 보이는 외모와 달리 북마크에는 상남자 되는 법, 연애초보가 하는 실수 등 진정한 남자로 태어나기 위한 정보가 즐비합니다. 입사 2주 만에 레이니스트에 빛보다 빠른 속도로 적응했습니다.
      card: 현대카드 M2 Edition2
      product: 신한 직장IN플러스적금 / 마이홈플랜 주택청약종합저축
    - name: 권수진
      position: Marketer
      email: sujin@rainist.com
      desc: 권수진님은 목소리가 큽니다. 밥 먹고 들어오는 길에 말하는 소리가 4층 사무실까지 들립니다. 하루에 약으로 카페라떼 5통을 먹어 치우며, 못 먹게 하면 금단현상 때문에 SNS 드립이 떠오르지 않는다며 목소리가 더 커집니다. 2016년 새해 소망으로 다이어트를 얘기했다가 대표님에게 카페라떼 중지령을 선포당했습니다.
      card: 우리 가득한 / 롯데 국민행복 / KB 혜담
      product: 우리 아가사랑 유후 적금 / 주택청약종합저축
    - name: 안성원
      position: Marketer
      email: sungwon@rainist.com
      desc: 안성원님은 수수깡입니다. 아무도 안 건드려도 엎어집니다. 맞은편 자리에서 갑자기 실종되는 경우도 있는데, 의자에 앉다가 엎어져서입니다. 레이니스트 공식 심신미약자로 뒷사람이 부르거나 어깨만 짚어도 놀라 자지러집니다. 참한 PR 담당자를 찾으려던 회사의 계획은 수포로 돌아간 듯합니다. 알파카를 닮았습니다.
      card: 신한 Love / 신세계 씨티 리워드
      product: 국민은행 Smart★폰 적금
